### PR TITLE
Piskel animated preview script rework + new features

### PR DESCRIPTION
**Pull request by david-szabo97**
- Fixed framesheets being loaded multiple times at gallery preview.
- Added a "Loading ..." text for previews. (GIF made with 50kbps throttle)
  Piskel Animated Preview Loading
- Fixed an issue about animated previews being loaded when there is only a single frame.
- Added progress bar for animated previews.
  Piskel Animated Preview Progress Bar
  Piskel Animated Preview Progress Bar

### CODE REVIEW

**Comment by david-szabo97** [comment]
Here is a preview of an experimental one: (It's a bit buggy but enough for now :smile:)
If the full animated preview's animation time is lower than a certain threshold (right now 1sec) it shows a full progress bar rather than animating.
Action menu and progress bar moves when the mouse is below or over the half of the canvas height, so you can see the bottom/top pixels if you want.
New design for progress bar
What do you think? @juliandescottes 
Animated Preview Experiment

**Comment by juliandescottes** [comment]
The new height is much better! Thanks.

General feedback:
- I would leave the progress bar on the top and the actions on the bottom. Otherwise I'm afraid users might misclick the progress bar when trying to click on a button and vice-versa. Let's keep them separate as in your first proposal.
- not a big fan of moving the UI depending on the cursor position. I would prefer the UI elements to remain at the same position
- the black bars really stand out, maybe use a different shade of blue instead of black ?
- one second threshold seems fine

**Comment by david-szabo97** [comment]
Thank you for the feedback :smile:

**Review by luongquangthai221279 — CHANGES_REQUESTED** [review]
Báo cáo thay đổi

**Pull request closed without merging**
